### ISSUE TITLE
Email on catalog show view is not working

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/etda#65]

**Comment by cam156** [comment]
Need to fix error on servers by adding a line into production environment like: https://github.com/psu-stewardship/etda/blob/master/config/environments/development.rb#L19

```
ArgumentError (An SMTP From address is required to send a message. Set the message smtp_envelope_from, return_path, sender, or from address.):
  mail (2.6.3) lib/mail/check_delivery_params.rb:5:in `check_delivery_params'
  mail (2.6.3) lib/mail/network/delivery_methods/test_mailer.rb:39:in `deliver!'
  mail (2.6.3) lib/mail/message.rb:2141:in `do_delivery'
  mail (2.6.3) lib/mail/message.rb:236:in `block in deliver'
  actionmailer (4.2.4) lib/action_mailer/base.rb:543:in `block in deliver_mail'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionmailer (4.2.4) lib/action_mailer/base.rb:541:in `deliver_mail'
  mail (2.6.3) lib/mail/message.rb:236:in `deliver'
  actionmailer (4.2.4) lib/action_mailer/message_delivery.rb:85:in `deliver_now'
  blacklight (5.16.3) app/controllers/concerns/blacklight/catalog.rb:261:in `email_action'
  blacklight (5.16.3) app/controllers/concerns/blacklight/default_component_configuration.rb:48:in `block in add_show_tools_partial'
```

**Comment by cam156** [comment]
Confirmed with @jonibar that the email from the catalog is working
